spring:
  application:
    name: report-ms
  profiles:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777" #De aqui se conecta al config server para leer el value
server:
  servlet:
    context-path: /report-ms
  port: 7070
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
